version: '3'

services:
  hyperion-exchange:
    image: nint8835/hyperion-exchange
    restart: always
    networks:
      - web
    expose:
      - 3000
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host: hyperion.bootleg.technology"
      traefik.port: 3000
      traefik.frontend.entryPoints: "https"
networks:
  web:
    external: true